[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn cameo_backend.wsgi:application --log-file -"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicy = "on-failure"
maxRetries = 10

[env]
PYTHON_VERSION = "3.12"
DJANGO_SETTINGS_MODULE = "cameo_backend.settings"
PYTHONPATH = "."
DJANGO_DEBUG = "False"
PORT = "8000"
DJANGO_ALLOWED_HOSTS = ".railway.app,localhost,127.0.0.1,0.0.0.0"
DATABASE_URL = ""
SECRET_KEY = "django-insecure-aedqw23rwea-=0ewqaeqwd13d1312"
WEB_CONCURRENCY = "2" 