[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn cameo_backend.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 300

[deploy.envs]
PORT = "8000" 