name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          
      - name: Install Python dependencies
        run: |
          cd cameo_backend
          pip install -r requirements.txt
          
      - name: Build React frontend
        run: |
          cd cameo_frontend
          npm install
          npm run build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cameo_frontend/build
          
      - name: Create backend deployment package
        run: |
          cd cameo_backend
          zip -r ../backend.zip . -x "*.pyc" "__pycache__/*" "venv/*" "*.env"
          
      - name: Upload backend package
        uses: actions/upload-artifact@v2
        with:
          name: backend-package
          path: backend.zip 