name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Directory Structure
        run: |
          pwd
          ls -la
          echo "Checking cameo_backend directory:"
          ls -la cameo_backend || echo "cameo_backend directory not found"
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Python dependencies
        run: |
          cd cameo_backend
          pip install -r requirements.txt
          
      - name: Build React frontend
        run: |
          cd cameo_backend/cameo_frontend
          npm install
          npm run build
          
      - name: Collect static files
        run: |
          cd cameo_backend
          python manage.py collectstatic --noinput
          
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          railway --version
          
      - name: Debug Railway CLI
        run: |
          which railway
          railway --version
          
      - name: Login to Railway
        run: |
          railway login --browserless
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          
      - name: Debug Railway Login
        run: |
          railway whoami
          
      - name: Deploy to Railway
        run: |
          cd cameo_backend
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          railway up --service cameo-game --debug
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          PYTHONUNBUFFERED: 1
          RAILWAY_DEBUG: 1 