name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Railway
        run: |
          npm install -g @railway/cli
          echo "$(npm config get prefix)/bin" >> $GITHUB_PATH
          
      - name: Debug Railway CLI
        run: |
          echo "Railway CLI version:"
          railway --version
          if [ -n "${{ secrets.RAILWAY_TOKEN }}" ]; then
            echo "RAILWAY_TOKEN environment variable is set (masked for security)"
            echo "Token length: ${#RAILWAY_TOKEN} characters"
          else
            echo "RAILWAY_TOKEN is not set!"
          fi
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      
      - name: Deploy with Railway CLI using Docker
        uses: docker://ghcr.io/railwayapp/cli:latest
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          args: up --detach

