name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Directory Structure
        run: |
          pwd
          ls -la
          echo "Checking cameo_backend directory:"
          ls -la cameo_backend || echo "cameo_backend directory not found"
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          cd cameo_backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build React frontend
        run: |
          cd cameo_backend/cameo_frontend
          npm install
          npm run build
          
      - name: Collect static files
        run: |
          cd cameo_backend
          python manage.py collectstatic --noinput
          
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Debug Railway CLI
        run: |
          which railway
          railway --version
          
      - name: Authenticate with Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          mkdir -p ~/.railway
          echo "{\"token\":\"$RAILWAY_TOKEN\"}" > ~/.railway/config.json
          chmod 600 ~/.railway/config.json
          railway whoami || echo "Token verification failed"
          
      - name: Link Railway Project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd cameo_backend
          echo "Current directory: $(pwd)"
          echo "Attempting to link project..."
          railway link ${{ secrets.RAILWAY_PROJECT_ID }}
          
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_DEBUG: 1
          RAILWAY_TIMEOUT: 300000
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        run: |
          cd cameo_backend
          echo "Current directory: $(pwd)"
          echo "Starting deployment..."
          railway up --service ${{ secrets.RAILWAY_SERVICE_NAME }} --detach 