name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Directory Structure
        run: |
          pwd
          ls -la
          echo "Checking cameo_backend directory:"
          ls -la cameo_backend || echo "cameo_backend directory not found"
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          cd cameo_backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build React frontend
        run: |
          cd cameo_backend/cameo_frontend
          npm install
          npm run build
          
      - name: Collect static files
        run: |
          cd cameo_backend
          python manage.py collectstatic --noinput
          
      - name: Install Railway CLI
        run: |
          npm install -g @railway/cli
          echo "Adding npm global bin to PATH"
          echo "export PATH=$PATH:$(npm config get prefix)/bin" >> $GITHUB_ENV
          source $GITHUB_ENV
          
      - name: Debug Railway CLI
        run: |
          echo "Current PATH: $PATH"
          which railway || echo "railway not found in PATH"
          railway --version || echo "railway version check failed"
          
      - name: Authenticate with Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          mkdir -p ~/.railway
          echo "{\"token\":\"$RAILWAY_TOKEN\"}" > ~/.railway/config.json
          chmod 600 ~/.railway/config.json
          railway whoami || echo "Token verification failed"
          
      - name: Link Railway Project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          cd cameo_backend
          echo "Current directory: $(pwd)"
          echo "Attempting to link project..."
          
          # First try to list projects to verify authentication
          railway projects || {
            echo "Failed to list projects. Authentication may have failed."
            exit 1
          }
          
          # Try to link with project ID if available
          if [ -n "$RAILWAY_PROJECT_ID" ]; then
            echo "Project ID found, attempting to link..."
            railway link "$RAILWAY_PROJECT_ID" || {
              echo "Failed to link with project ID. Creating new project..."
              railway init --name "cameo-game" || {
                echo "Failed to create new project"
                exit 1
              }
            }
          else
            echo "No project ID found. Creating new project..."
            railway init --name "cameo-game" || {
              echo "Failed to create new project"
              exit 1
            }
          fi
          
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_DEBUG: 1
          RAILWAY_TIMEOUT: 300000
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        run: |
          cd cameo_backend
          echo "Current directory: $(pwd)"
          echo "Starting deployment..."
          railway up --detach 