name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Directory Structure
        run: |
          pwd
          ls -la
          echo "Checking cameo_backend directory:"
          ls -la cameo_backend || echo "cameo_backend directory not found"
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          cd cameo_backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build React frontend
        run: |
          cd cameo_backend/cameo_frontend
          npm install
          npm run build
          
      - name: Collect static files
        run: |
          cd cameo_backend
          python manage.py collectstatic --noinput
          
          
      - name: Install Railway CLI
        run: |
          npm install -g @railway/cli
          echo "Adding npm global bin to PATH"
          echo "PATH=$PATH:$(npm config get prefix)/bin" >> $GITHUB_ENV
          
      - name: Debug Railway CLI
        run: |
          echo "Current PATH: $PATH"
          which railway || echo "railway not found in PATH"
          railway --version || echo "railway version check failed"
          
      - name: Authenticate with Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "Authenticating with Railway..."
          echo "$RAILWAY_TOKEN" | railway login --browserless || {
            echo "Authentication failed. Check token validity."
            exit 1
          }
          railway whoami
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_DEBUG: 1
          RAILWAY_TIMEOUT: 300000
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        run: |
          cd cameo_backend
          echo "Current directory: $(pwd)"
          echo "Starting deployment..."
          railway up --detach 